seo:
  title:
    default: Simple Template for Astro
    template: "%s — Template"
  description: Description of the site
  robots:
    noindex: false
    nofollow: false
  og:
    title: My Simple Template
    type: website
    image:
      name: og-image.png
      width: 960
      height: 720
      alt: OpenGraph Image Alt
  twitter:
    card: summary_large_image
    title: My Simple Template
    description: Description of the site
    site: "@onwidget"
    handle: "@onwidget"
